### ISSUE TITLE
Add Support for Razer Naga Pro

### ISSUE THREAD

**Issue by ShadowKitty42** [Tekk-Know/RazerBatteryTaskbar#15]
I see you have the Pro V2 already, how difficult would it be to add the original model? That's the one I have and would love to use this software.

https://www.amazon.com/gp/product/B08D27XXRY/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by DrissiReda** [comment]
I have the same mouse. It doesn't work however it should because it has the same productId and transactionId as the V2 (0090 and 001f respectively). It doesn't even show up in devices. Only the wireless dock shows up for me.

Wondering if there is something else to change besides the transaction and product Ids found in main.js file.

**Comment by Tekk-Know** [comment]
@DrissiReda if the transaction Ids are the same then I would think it would be working. Are you sure this is connecting with USB and not Bluetooth?

**Comment by DrissiReda** [comment]
yes the naga pro v2 and v1 have the same transaction ids respectively for usb and wireless (only tried 2.4 not BT). 

You can see so here: https://github.com/openrazer/openrazer/blob/master/driver/razermouse_driver.c#L663

And the productId is also the same as you can see here: https://github.com/openrazer/openrazer/blob/master/README.md?plain=1#L179

**Comment by Tekk-Know** [comment]
Can you load up the debug version and give me the output from the popup?
https://github.com/Tekk-Know/RazerBatteryTaskbar/releases/tag/v1.0.1

**Comment by DrissiReda** [comment]
> @ShadowKitty42 @DrissiReda Can you load up the debug version and give me the output from the popup? https://github.com/Tekk-Know/RazerBatteryTaskbar/releases/tag/v1.0.1

How to load up debug? 

launching it normally without any arguments returns this output:

```
NamedError [NotFoundError]: Failed to execute 'requestDevice' on 'USB': No device selected.
    at WebUSB.requestDevice (C:\Users\FOO\AppData\Local\razerbatterytaskbar\app-1.0.7\resources\app\node_modules\usb\dist\webusb\index.js:163:19)
    at async GetMouse (C:\Users\FOO\AppData\Local\razerbatterytaskbar\app-1.0.7\resources\app\src\main.js:180:20)
    at async GetBattery (C:\Users\FOO\AppData\Local\razerbatterytaskbar\app-1.0.7\resources\app\src\main.js:192:23)
```

**Comment by ShadowKitty42** [comment]
I didn't even realize there was a Debug version, I got this same popup while modifying it myself to try and figure it out lol

Either way, here's what comes up for me
![image_2024-07-04_120741207](https://github.com/Tekk-Know/RazerBatteryTaskbar/assets/3394296/d6d11443-0193-4730-ba9b-c5a087d89986)

**Comment by Tekk-Know** [comment]
You guys might try the debug rewrite release and see if it fixes anything for you:
https://github.com/Tekk-Know/RazerBatteryTaskbar/releases/download/debug/razerbatterytaskbar-1.0.9.Setup.exe

**Comment by DrissiReda** [comment]
> You guys might try the debug rewrite release and see if it fixes anything for you: https://github.com/Tekk-Know/RazerBatteryTaskbar/releases/download/debug/razerbatterytaskbar-1.0.9.Setup.exe

Running this command in terminal without any arguments: `.\razerbatterytaskbar.exe` gives:

```bash
TypeError: Cannot read properties of undefined (reading 'transactionId')
    at GetMessage (C:\Users\NEW HORYZEN\AppData\Local\razerbatterytaskbar\app-1.0.9\resources\app\src\main.js:71:40)
    at C:\Users\NEW HORYZEN\AppData\Local\razerbatterytaskbar\app-1.0.9\resources\app\src\main.js:102:25
    at new Promise (<anonymous>)
    at GetBattery (C:\Users\NEW HORYZEN\AppData\Local\razerbatterytaskbar\app-1.0.9\resources\app\src\main.js:98:12)
    at SetTrayDetails (C:\Users\NEW HORYZEN\AppData\Local\razerbatterytaskbar\app-1.0.9\resources\app\src\main.js:51:5)
    at C:\Users\NEW HORYZEN\AppData\Local\razerbatterytaskbar\app-1.0.9\resources\app\src\main.js:34:5
```

**Comment by ShadowKitty42** [comment]
Well that's interesting. I'm also getting the same message, "cannot read properties", but I'm also getting this

![image](https://github.com/Tekk-Know/RazerBatteryTaskbar/assets/3394296/777436f2-f253-4c54-8708-5877a115e0b1)

And when hovering on the icon, it says searching for devices
